### PR TITLE
Bug fix: gnome-screensaver is not detected. If-statment compared string to integer.

### PR DESCRIPTION
**Pull request by gschwaer**

### CODE REVIEW

**Comment by devkral** [comment]
This commit doesn't make sense. 2> redirects the error stream and is correct. This breaks the check.
Maybe you have gnome-screensaver installed but you use a different screensaver. Anyway the check can be removed (gnome-screensaver-tool is not used anymore). Should fix your problem too.

**Comment by gschwaer** [comment]
The Value for the test -q 0 is generated by echo $? . If stdout is not redirected to /dev/null the subshell evaluates to a concatenated string and bash tests "/use/bin/gnome-screensaver-command 0" -q "0". Which never works.
I'm still using the gnome-screensaver and lights on+.sh responds with something like "no screensaver detected". If I change this line it works.

**Comment by gschwaer** [comment]
You can also see on your system with `less $(which which)`, that `which` will never produce an output on stderr.

**Comment by devkral** [comment]
I see. Should be &>. But anyway I removed the check entirely and use dbus. Does the new version work?

**Comment by gschwaer** [comment]
Haven't tested in detail, but the server script starts to mainloop without failure.

**Pull request closed without merging**
